### ISSUE TITLE
Bygging på Pi, take 1

### ISSUE THREAD

**Issue by geirsagberg** [bekk/bekkboard#9]
GUI og server skal kjøre på raspberry pi med enlinje-deploy

**Comment by torgeir** [comment]
Good enough for første runde;
- Repoet ligger som et "bare"-repo på pien og har en git `post-receive` hook som kjører npm install i `GUI/`, `server/` og `hardware/`når man pusher til `git push pi master`.
- GUI bygges lokalt på utviklerpc (det er så tregt på pien) og scp'es opp med å kjøre `./deploy` fra `GUI`-katalogen

Server restartes med `sudo restart bekkboard-api`.
Gui restartes ved deploy, men kan også restaretes tilsvarende med `sudo restart bekkboard-gui`.

Alt starter når pien booter.

**Comment by torgeir** [comment]
Readme oppdatert med info.
